# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 16:43
from __future__ import unicode_literals

import calcloot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('hashtag', models.CharField(editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('rate', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='benefactors',
            field=models.ManyToManyField(related_name='benefactors', to='calcloot.Person', verbose_name=b'persons benefiting'),
        ),
        migrations.AddField(
            model_name='expense',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcloot.Calculation'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcloot.Currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='person',
            field=calcloot.models.UnsavedForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paying', to='calcloot.Person', verbose_name=b'person who paid'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcloot.Currency'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='involved',
            field=models.ManyToManyField(related_name='involved', to='calcloot.Person', verbose_name=b'persons involved'),
        ),
    ]
