# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 16:47
from __future__ import unicode_literals

import calcloot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcloot', '0002_auto_20160106_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='currency',
            field=models.ForeignKey(default=calcloot.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, to='calcloot.Currency'),
        ),
    ]
