# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcloot', '0003_auto_20160106_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
